controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app_afficher_message:
    path: /afficher/message
    controller: App\Controller\HomeController::afficherMessage
app_bonjour_bis:
    path: /bonjour/bis/{user}
    controller: App\Controller\HomeController::bonjourBis
app_calculate:
    path: /calculate/{nbr1}/{nbr2}/{operateur}
    controller: App\Controller\HomeController::calculate